In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [5]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [6]:
X = df.drop(columns=['Survived'])
y = df["Survived"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [8]:
knn = KNNImputer(n_neighbors=10, weights="distance")

In [9]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [10]:
X_train_trf

array([[ 45.5   ,   1.    ,  28.5   ],
       [ 23.    ,   2.    ,  13.    ],
       [ 32.    ,   3.    ,   7.925 ],
       ...,
       [ 41.    ,   3.    ,  14.1083],
       [ 14.    ,   1.    , 120.    ],
       [ 21.    ,   1.    ,  77.2875]], shape=(712, 3))

In [11]:
pd.DataFrame(X_test_trf, columns=X_train.columns)

      Age  Pclass     Fare
0    29.0     3.0  15.2458
1    31.0     2.0  10.5000
2    20.0     3.0   7.9250
3     6.0     2.0  33.0000
4    14.0     3.0  11.2417
..    ...     ...      ...
174  17.0     3.0   7.1250
175  29.5     3.0   7.2250
176  38.0     3.0  31.3875
177  17.0     2.0  10.5000
178   4.0     3.0  16.7000

[179 rows x 3 columns]

In [12]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)
accuracy_score(y_test, y_pred)

0.7374301675977654

In [13]:
# Comparision with Simple Imputer --> mean
from sklearn.impute import SimpleImputer
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.7374301675977654