In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("smartphone_data.csv")

In [3]:
df.head()

   camera  age  ram  cpu_score  slot_sd  sims  price
0     110    0   16         95        0     2  13727
1     187    0   12         44        0     2  23907
2     100    1    8         99        1     2  21288
3      22    0   16         65        1     1  42195
4     114    2   16         55        0     2  27894

In [4]:
df.shape

(10000, 7)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   camera     10000 non-null  int64
 1   age        10000 non-null  int64
 2   ram        10000 non-null  int64
 3   cpu_score  10000 non-null  int64
 4   slot_sd    10000 non-null  int64
 5   sims       10000 non-null  int64
 6   price      10000 non-null  int64
dtypes: int64(7)
memory usage: 547.0 KB

In [6]:
df.describe().round()

        camera      age      ram  cpu_score  slot_sd     sims    price
count  10000.0  10000.0  10000.0    10000.0  10000.0  10000.0  10000.0
mean     105.0      1.0      9.0       70.0      0.0      2.0  39216.0
std       56.0      1.0      4.0       18.0      1.0      0.0  17817.0
min        8.0      0.0      4.0       40.0      0.0      1.0   8000.0
25%       57.0      0.0      6.0       55.0      0.0      1.0  23738.0
50%      106.0      1.0      8.0       70.0      0.0      2.0  39234.0
75%      154.0      3.0     12.0       85.0      1.0      2.0  54706.0
max      200.0      3.0     16.0      100.0      1.0      2.0  69998.0

In [8]:
pd.datasets

AttributeError: module 'pandas' has no attribute 'datasets'