In [1]:
import pandas as pd
import numpy as np

In [29]:
df2 = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv")
df1 = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv")
df = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv")

In [3]:
df.sample(5)

    age  gender   review education purchased
1    68  Female     Poor        UG        No
10   98  Female     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
34   86    Male  Average    School        No

In [4]:
df = df.iloc[:, 2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

In [6]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"],["School", "UG", "PG"]])
oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [7]:
X_train

array([[2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.]])

In [8]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [10]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [11]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1])

Using Column Transformer

In [12]:
df1.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [16]:
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [36]:
y_train.head()

28     No
11    Yes
10    Yes
41    Yes
2      No
Name: purchased, dtype: object

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [23]:
ordinal_encoding = Pipeline(steps=[
    ('ordinal_encoder', OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]))
])

label_encoding = Pipeline(steps=[
    ('label_encoder', LabelEncoder())
])

In [39]:
full_pipeline = ColumnTransformer(transformers=[
    ('ordinal_encoding', ordinal_encoding, ['review', 'education']),
    ('label_encoding', label_encoding, ['purchased'])
])

In [30]:
full_pipeline

ColumnTransformer(transformers=[('ordinal_encoding',
                                 Pipeline(steps=[('ordinal_encoder',
                                                  OrdinalEncoder(categories=[['Poor',
                                                                              'Average',
                                                                              'Good'],
                                                                             ['School',
                                                                              'UG',
                                                                              'PG']]))]),
                                 ['review', 'education']),
                                ('label_encoding',
                                 Pipeline(steps=[('label_encoder',
                                                  LabelEncoder())]),
                                 ['purchased'])])

In [45]:
df2.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [48]:
df2 = df2.iloc[:, 1]

In [50]:
from sklearn.model_selection import train_test_split
X = df2.iloc[:, 1]
y = df2.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

IndexingError: Too many indexers